import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, CalendarDays, ChevronRight, Clock3, Flame, MapPin, Menu, Search, ShieldCheck, Sparkles, Ticket, UserRound, X, Zap } from 'lucide-react';
import './styles.css';

const events = [
  { id:'sunidhi', title:'Sunidhi Chauhan Live', subtitle:'Live in Surat', date:'03 OCT 2026', time:'08:00 PM', location:'Surat, Gujarat', price:2235, tag:'TRENDING', progress:82, image:'linear-gradient(135deg,#071a3d 0%,#174aa6 48%,#62a7ff 100%)', accent:'SUNIDHI', category:'Concerts' },
  { id:'navratri', title:'Navratri Night', subtitle:'The Grand Celebration', date:'10 OCT 2026', time:'07:30 PM', location:'Surat, Gujarat', price:999, tag:'MNG DROP', progress:64, image:'linear-gradient(135deg,#1b0934 0%,#4c1d95 48%,#f59e0b 100%)', accent:'NAVRATRI', category:'Festivals' },
  { id:'afterdark', title:'MNG After Dark', subtitle:'The Midnight Edition', date:'17 OCT 2026', time:'09:00 PM', location:'Surat, Gujarat', price:1499, tag:'NEW', progress:39, image:'linear-gradient(135deg,#020617 0%,#0f172a 45%,#2563eb 100%)', accent:'AFTER DARK', category:'Nightlife' },
  { id:'festival', title:'City Lights Festival', subtitle:'Music • Food • Culture', date:'24 OCT 2026', time:'06:00 PM', location:'Ahmedabad, Gujarat', price:799, tag:'COMING SOON', progress:21, image:'linear-gradient(135deg,#071b2d 0%,#0e7490 55%,#67e8f9 100%)', accent:'CITY LIGHTS', category:'Festivals' },
];

const categories = [{name:'Concerts',icon:'🎤'},{name:'Festivals',icon:'🎉'},{name:'Nightlife',icon:'🌙'},{name:'Shows',icon:'🎭'},{name:'Experiences',icon:'✨'},{name:'Sports',icon:'🏟'}];

type Nav=(to:string)=>void;

function money(n:number){ return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n); }
function path(){ return window.location.pathname+window.location.search+window.location.hash; }
function scrollToHash(hash:string){ const el=hash?document.getElementById(hash.slice(1)):null; if(el) el.scrollIntoView({behavior:'smooth',block:'start'}); else window.scrollTo(0,0); }

function App(){
  const [route,setRoute] = useState(path());
  const [menu,setMenu] = useState(false);
  const navigate:Nav=(to)=>{ const same=new URL(to,window.location.origin).href===window.location.href; history.pushState({},'',to); setMenu(false); if(same) scrollToHash(window.location.hash); else setRoute(path()); };
  React.useEffect(()=>{ const h=()=>setRoute(path()); addEventListener('popstate',h); return()=>removeEventListener('popstate',h)},[]);
  // Scroll to the requested section (e.g. /#radar) once the target page has rendered.
  React.useEffect(()=>{ scrollToHash(window.location.hash); },[route]);
  const url=new URL(route,window.location.origin); const pathname=url.pathname.replace(/\/+$/,'')||'/';
  const header={navigate,menu,setMenu};
  if(pathname.startsWith('/admin')) return <Admin navigate={navigate}/>;
  if(pathname.startsWith('/partner')) return <Partner navigate={navigate}/>;
  if(pathname==='/events') return <EventsPage {...header} query={url.searchParams.get('q')||''} category={url.searchParams.get('category')||''} focusSearch={url.searchParams.has('search')}/>;
  if(pathname.startsWith('/events/')) return <EventPage {...header} id={pathname.split('/')[2]}/>;
  return <Home {...header}/>;
}

function Header({navigate,menu,setMenu}:{navigate:(s:string)=>void,menu:boolean,setMenu:(v:boolean)=>void}){
 return <header className="topbar">
   <button className="brand" onClick={()=>navigate('/')}><span className="brand-orbit">✦</span><span>MARS NOVA</span></button>
   <nav className="desktop-nav"><button onClick={()=>navigate('/#events')}>Events</button><button onClick={()=>navigate('/#categories')}>Categories</button><button onClick={()=>navigate('/#radar')}>MNG Radar</button><button onClick={()=>navigate('/partner')}>Partners</button></nav>
   <div className="nav-actions"><button className="icon-btn" aria-label="Search events" onClick={()=>navigate('/events?search')}><Search size={18}/></button><button className="ticket-link" onClick={()=>navigate('/partner')}><Ticket size={16}/> Partner</button><button className="avatar" aria-label="Profile / sign in" onClick={()=>navigate('/partner')}><UserRound size={17}/></button><button className="mobile-menu icon-btn" aria-label="Menu" onClick={()=>setMenu(!menu)}>{menu?<X size={20}/>:<Menu size={20}/>}</button></div>
   {menu && <div className="mobile-nav"><button onClick={()=>navigate('/#events')}>Events</button><button onClick={()=>navigate('/#radar')}>MNG Radar</button><button onClick={()=>navigate('/#categories')}>Categories</button><button onClick={()=>navigate('/events?search')}>Search</button><button onClick={()=>navigate('/partner')}>Partner Login</button></div>}
 </header>
}

function Home({navigate,menu,setMenu}:{navigate:(s:string)=>void,menu:boolean,setMenu:(v:boolean)=>void}){
 return <div><Header navigate={navigate} menu={menu} setMenu={setMenu}/><main>
   <section className="hero-shell"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> MNG RADAR · SURAT</div><h1>Your next<br/><span>experience</span> awaits.</h1><p>Discover concerts, festivals and nights worth remembering — all in one trusted place.</p><div className="hero-actions"><button className="primary" onClick={()=>navigate('/events')}>Explore events <ArrowRight size={18}/></button><button className="ghost" onClick={()=>navigate('/#how-it-works')}>How MNG works <ChevronRight size={17}/></button></div><div className="trust-row"><span><ShieldCheck size={16}/> Secure checkout</span><span><Zap size={16}/> Instant QR ticket</span></div></div><div className="hero-art"><div className="hero-glow"/><div className="hero-poster"><div className="poster-mini">MNG<br/><b>LIVE</b></div><div className="poster-title">SUNIDHI<br/><span>CHAUHAN</span></div><div className="poster-meta">03 OCT · SURAT</div><div className="poster-stamp">LIVE<br/>2026</div></div><div className="floating-stat"><Flame size={16}/> 31 people are viewing</div></div></section>
   <section className="section" id="events"><div className="section-head"><div><div className="kicker">DISCOVER</div><h2>Trending in Surat</h2></div><button className="text-btn" onClick={()=>navigate('/events')}>View all <ArrowRight size={16}/></button></div><div className="event-grid">{events.slice(0,3).map(e=><EventCard key={e.id} e={e} navigate={navigate}/>)}</div></section>
   <section className="section radar" id="radar"><div className="section-head"><div><div className="kicker">REAL-TIME</div><h2>MNG Radar</h2></div><div className="radar-live"><span className="live-dot"/> Live</div></div><div className="radar-grid">{events.map(e=><div className="radar-item" key={e.id} onClick={()=>navigate('/events/'+e.id)}><div className="radar-name"><span>{e.title}</span><b>{e.progress}%</b></div><div className="bar"><i style={{width:e.progress+'%'}}/></div><small>{e.progress>75?'Final release':'Tickets moving'}</small></div>)}</div></section>
   <section className="section" id="categories"><div className="section-head"><div><div className="kicker">EXPLORE</div><h2>Find your scene</h2></div></div><div className="chips">{categories.map(c=><button key={c.name} onClick={()=>navigate('/events?category='+encodeURIComponent(c.name))}>{c.icon} {c.name}</button>)}</div></section>
   <section className="section"><div className="section-head"><div><div className="kicker">UP NEXT</div><h2>More experiences</h2></div></div><div className="event-grid two">{events.slice(2).map(e=><EventCard key={e.id} e={e} navigate={navigate}/>)}</div></section>
   <section className="section" id="how-it-works"><div className="section-head"><div><div className="kicker">HOW IT WORKS</div><h2>How MNG works</h2></div></div><div className="how-grid">{[{icon:<Search size={20}/>,title:'Discover',text:'Browse verified concerts, festivals and nights across Gujarat.'},{icon:<Ticket size={20}/>,title:'Choose your pass',text:'Pick Silver, Gold or Fanpit and the number of tickets you need.'},{icon:<ShieldCheck size={20}/>,title:'Pay securely',text:'Prices and inventory are revalidated on the server before payment.'},{icon:<Zap size={20}/>,title:'Get your QR',text:'Your digital ticket with a unique QR code is issued instantly.'}].map((s,i)=><div className="how-step" key={s.title}><span className="how-icon">{s.icon}</span><small>STEP {i+1}</small><h3>{s.title}</h3><p>{s.text}</p></div>)}</div><div className="hero-actions"><button className="primary" onClick={()=>navigate('/events')}>Explore events <ArrowRight size={18}/></button><button className="ghost" onClick={()=>navigate('/partner')}>Become a partner <ChevronRight size={17}/></button></div></section>
 </main><footer><div className="footer-brand">✦ MARS NOVA</div><p>Events · Experiences · Memories</p><span>© 2026 Mars Nova Global</span></footer></div>
}

function EventsPage({navigate,menu,setMenu,query,category,focusSearch}:{navigate:Nav,menu:boolean,setMenu:(v:boolean)=>void,query:string,category:string,focusSearch:boolean}){
 const [q,setQ]=useState(query);
 React.useEffect(()=>setQ(query),[query]);
 const results=useMemo(()=>{const t=q.trim().toLowerCase(); return events.filter(e=>(!category||e.category===category)&&(!t||[e.title,e.subtitle,e.location,e.category].some(v=>v.toLowerCase().includes(t))));},[q,category]);
 const withParams=(cat:string)=>{const p=new URLSearchParams(); if(q.trim()) p.set('q',q.trim()); if(cat) p.set('category',cat); const s=p.toString(); return '/events'+(s?'?'+s:'');};
 return <div><Header navigate={navigate} menu={menu} setMenu={setMenu}/><main className="event-page">
   <button className="back" onClick={()=>navigate('/')}>← Back to home</button>
   <div className="section-head"><div><div className="kicker">{category?category.toUpperCase():'ALL EVENTS'}</div><h2 className="page-title">{category||'Explore events'}</h2></div></div>
   <label className="search-box"><Search size={18}/><input autoFocus={focusSearch} value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter') history.replaceState({},'',withParams(category));}} placeholder="Search events, artists or cities"/>{q&&<button aria-label="Clear search" onClick={()=>setQ('')}><X size={16}/></button>}</label>
   <div className="chips"><button className={!category?'active':''} onClick={()=>navigate(withParams(''))}>All</button>{categories.map(c=><button key={c.name} className={category===c.name?'active':''} onClick={()=>navigate(withParams(c.name))}>{c.icon} {c.name}</button>)}</div>
   {results.length?<div className="event-grid results">{results.map(e=><EventCard key={e.id} e={e} navigate={navigate}/>)}</div>:<div className="empty results"><Sparkles size={28}/><h2>No events found</h2><p>{category?`Nothing in ${category} yet${q?` matching “${q}”`:''}.`:`No events match “${q}”.`} Try another search or category.</p><button className="ghost" onClick={()=>{setQ('');navigate('/events');}}>Show all events</button></div>}
 </main></div>
}

function EventCard({e,navigate}:{e:any,navigate:(s:string)=>void}){return <article className="event-card" onClick={()=>navigate('/events/'+e.id)}><div className="event-image" style={{background:e.image}}><div className="poster-word">{e.accent}</div><span className="tag">{e.tag}</span><span className="heart">♡</span><div className="date-badge"><b>{e.date.split(' ')[0]}</b><span>{e.date.split(' ')[1]}</span></div></div><div className="event-body"><div className="event-title"><h3>{e.title}</h3><ArrowRight size={17}/></div><p>{e.subtitle}</p><div className="event-meta"><span><CalendarDays size={14}/>{e.date}</span><span><MapPin size={14}/>{e.location}</span></div><div className="event-bottom"><span>From <b>{money(e.price)}</b></span><span className="availability"><span className="mini-bar"><i style={{width:e.progress+'%'}}/></span>{e.progress}% moving</span></div></div></article>}

function EventPage({navigate,menu,setMenu,id}:{navigate:Nav,menu:boolean,setMenu:(v:boolean)=>void,id:string}){const e=events.find(x=>x.id===id)||events[0]; const [qty,setQty]=useState(1); const [selected,setSelected]=useState('Silver'); const passes=[{name:'Silver',price:e.price,desc:'Standard entry'},{name:'Gold',price:Math.round(e.price*1.55),desc:'Premium area'},{name:'Fanpit',price:Math.round(e.price*2.2),desc:'Closest to the action'}]; const current=passes.find(p=>p.name===selected)!; return <div><Header navigate={navigate} menu={menu} setMenu={setMenu}/><main className="event-page"><button className="back" onClick={()=>navigate('/events')}>← Back to events</button><div className="event-hero"><div className="big-art" style={{background:e.image}}><div className="big-word">{e.accent}</div><span className="tag">{e.tag}</span></div><div className="event-info"><div className="kicker">MNG VERIFIED EVENT</div><h1>{e.title}</h1><p className="subtitle">{e.subtitle}</p><div className="info-list"><span><CalendarDays/>{e.date} · {e.time}</span><span><MapPin/>{e.location}</span></div><p className="description">An unforgettable night curated by Mars Nova Global. Your digital ticket is generated instantly after successful payment and protected by a unique QR.</p><div className="event-fomo"><Flame size={16}/> {e.progress}% of the currently released inventory is moving</div></div></div><section className="booking"><div><div className="kicker">CHOOSE YOUR PASS</div><h2>Make it your night.</h2>{passes.map(p=><button key={p.name} className={'pass-row '+(selected===p.name?'selected':'')} onClick={()=>setSelected(p.name)}><span><b>{p.name}</b><small>{p.desc}</small></span><strong>{money(p.price)}</strong></button>)}</div><aside className="order-card"><div className="order-top"><span>Your booking</span><Ticket size={18}/></div><div className="qty"><span>{selected}</span><div><button onClick={()=>setQty(Math.max(1,qty-1))}>−</button><b>{qty}</b><button onClick={()=>setQty(qty+1)}>+</button></div></div><div className="order-total"><span>Total</span><b>{money(current.price*qty)}</b></div><button className="primary full" onClick={()=>alert('Razorpay will be connected here after Supabase + server functions are configured.')}>Continue to secure payment <ArrowRight size={18}/></button><small className="secure"><ShieldCheck size={14}/> Price and inventory will be revalidated on the server before payment.</small></aside></section></main></div>}

function Admin({navigate}:{navigate:(s:string)=>void}){const [tab,setTab]=useState('Dashboard'); const tabs=['Dashboard','Events','Pass Types','Orders','Partners','Homepage','Marketing','Settings']; return <div className="portal"><aside className="sidebar"><button className="brand side-brand" onClick={()=>navigate('/')}>✦ MARS NOVA</button><div className="side-kicker">ADMIN CONSOLE</div>{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}<button className="side-back" onClick={()=>navigate('/')}>← Public website</button></aside><main className="portal-main"><div className="portal-top"><div><div className="kicker">ADMIN CONSOLE</div><h1>{tab}</h1></div><div className="admin-user">Owner · <b>MN ADMIN</b></div></div>{tab==='Dashboard'?<Dashboard onManage={()=>setTab('Events')}/>:tab==='Events'?<AdminEvents/>:tab==='Pass Types'?<PassManager/>:tab==='Partners'?<PartnerManager/>:<Coming title={tab}/>}</main></div>}
const notConnected=(action:string)=>alert(`${action} will be available once the admin console is connected to Supabase.`);
function Dashboard({onManage}:{onManage:()=>void}){return <><div className="stats"><Stat label="Gross sales" value="₹4,82,650"/><Stat label="Tickets sold" value="2,184"/><Stat label="Active events" value="6"/><Stat label="Check-ins" value="1,967"/></div><div className="admin-grid"><div className="panel"><div className="panel-head"><h3>Live events</h3><button className="primary small" onClick={onManage}>+ Add event</button></div>{events.map(e=><div className="admin-event" key={e.id}><div className="admin-thumb" style={{background:e.image}}/><div><b>{e.title}</b><small>{e.location} · {e.date}</small></div><span>{e.progress}% sold</span><button onClick={onManage}>Manage</button></div>)}</div><div className="panel"><div className="panel-head"><h3>Recent orders</h3></div>{['MNG-8219','MNG-8224','MNG-8231','MNG-8236'].map((x,i)=><div className="order-line" key={x}><span><b>{x}</b><small>{['Silver × 2','Gold × 1','Fanpit × 3','Silver × 1'][i]}</small></span><strong>{['₹4,470','₹3,465','₹14,751','₹2,235'][i]}</strong></div>)}</div></div></>}
function Stat({label,value}:{label:string,value:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>↑ 12.4% this week</small></div>}
function AdminEvents(){return <div className="panel"><div className="panel-head"><div><h3>Events</h3><small>Create, edit, publish and archive events.</small></div><button className="primary small" onClick={()=>notConnected('Creating events')}>+ Create event</button></div>{events.map(e=><div className="table-row" key={e.id}><div><b>{e.title}</b><small>{e.date} · {e.location}</small></div><span className="status">Published</span><span>{money(e.price)}+</span><button onClick={()=>notConnected('Editing '+e.title)}>Edit</button></div>)}</div>}
function PassManager(){const [price,setPrice]=useState('2235');return <div className="admin-grid"><div className="panel"><div className="panel-head"><div><h3>Pass types</h3><small>Prices are authoritative in the database.</small></div><button className="primary small" onClick={()=>notConnected('Adding pass types')}>+ Add pass</button></div>{['Silver','Gold','Fanpit'].map((n,i)=><div className="pass-admin" key={n}><div><b>{n}</b><small>{i===0?'Standard entry':i===1?'Premium area':'Closest to the action'}</small></div><label>Current price<input value={i===0?price:['3465','4917'][i-1]} onChange={i===0?e=>setPrice(e.target.value):undefined}/></label><span>Available {['642','491','388'][i]}</span><button onClick={()=>notConnected('Saving '+n+' pricing')}>Save</button></div>)}</div><div className="panel info-panel"><ShieldCheck size={24}/><h3>Price safety</h3><p>Customers never control the final amount. At checkout the server reads the current database price, validates inventory, calculates the total and only then creates the Razorpay order.</p><code>client price → server revalidation → Razorpay order</code></div></div>}
function PartnerManager(){return <div className="admin-grid"><div className="panel"><div className="panel-head"><div><h3>Partners</h3><small>Manage your verified reseller network.</small></div><button className="primary small" onClick={()=>notConnected('Adding partners')}>+ Add partner</button></div>{['Rahul Patel','Amit Shah','Jay Mehta','Karan Joshi'].map((n,i)=><div className="table-row" key={n}><div><b>{n}</b><small>MNGP10{24+i} · {i%2?'Standard':'VIP'} Partner</small></div><span className="status">Active</span><span>{[184,161,143,97][i]} tickets</span><button onClick={()=>notConnected('Managing '+n)}>Manage</button></div>)}</div><div className="panel info-panel"><Sparkles size={24}/><h3>Partner controls</h3><p>Each reseller will have a role-limited login, event access, custom pricing/commission rules, allocation limits, sales history and payment-link attribution.</p></div></div>}
function Coming({title}:{title:string}){return <div className="empty"><Sparkles size={28}/><h2>{title} module</h2><p>This section is scaffolded in the first build. Its data model and permissions will connect to Supabase next.</p></div>}
function Partner({navigate}:{navigate:(s:string)=>void}){const [logged,setLogged]=useState(false); const [tab,setTab]=useState('Overview');return <div className="portal partner-portal"><aside className="sidebar"><button className="brand side-brand" onClick={()=>navigate('/')}>✦ MARS NOVA</button><div className="side-kicker">PARTNER PORTAL</div>{['Overview','Sell Tickets','My Sales','My Links','Commission','Profile'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}<button className="side-back" onClick={()=>navigate('/')}>← Public website</button></aside><main className="portal-main">{!logged?<div className="login-card"><div className="login-mark">✦</div><div className="kicker">MNG VERIFIED PARTNER</div><h1>Sell tickets.<br/><span>Build your network.</span></h1><p>Sign in to your MNG Partner Portal. No app download required.</p><label>Partner ID<input placeholder="MNGP1024"/></label><label>Password<input type="password" placeholder="••••••••"/></label><button className="primary full" onClick={()=>setLogged(true)}>Sign in <ArrowRight size={18}/></button><small>Passwords are securely hashed. Admin can reset access at any time.</small></div>:tab!=='Overview'&&tab!=='Sell Tickets'?<><div className="portal-top"><div><div className="kicker">PARTNER PORTAL</div><h1>{tab}</h1></div><div className="admin-user">MNGP1024 · Rahul Patel</div></div><Coming title={tab}/></>:<><div className="portal-top"><div><div className="kicker">WELCOME BACK</div><h1>{tab==='Overview'?'Partner dashboard':tab}</h1></div><div className="admin-user">MNGP1024 · Rahul Patel</div></div><div className="stats"><Stat label="My sales" value="₹48,500"/><Stat label="Tickets sold" value="27"/><Stat label="Commission" value="₹5,430"/><Stat label="Pending" value="₹2,720"/></div><div className="panel"><div className="panel-head"><h3>Active events</h3></div>{events.slice(0,2).map(e=><div className="admin-event" key={e.id}><div className="admin-thumb" style={{background:e.image}}/><div><b>{e.title}</b><small>Partner price from {money(e.price-135)}</small></div><span>{e.progress}% moving</span><button onClick={()=>navigate('/events/'+e.id)}>Sell tickets</button></div>)}</div></>}</main></div>}

createRoot(document.getElementById('root')!).render(<App/>);
